### ISSUE TITLE
Undefined error on running script

### ISSUE THREAD

**Issue by hdsouza** [bryansh/lendingClubAPI#4]
Hi Bryan,
I tried  testing it out using the website (https://runkit.com/npm/node-lending-club-api)
and here is what I placed in the box:

var lc = require("node-lending-club-api");
lc.init({ apiKey: 'GVss----MY API Key -----eeBM=' });

When I click on RUN, I get an error "undefined"
Any Ideas

Thanks
Hil

**Comment by bryansh** [comment]
Hey Hil!

Sorry for not seeing this for a few days; I'm able to run the following code without issue on that site:

```
var nodeLendingClubApi = require("node-lending-club-api")

nodeLendingClubApi.init({ apiKey: 'cu------------------------A=' });

console.log('hi');
```

When I didn't have the console.log statement at the error; I did the word `undefined` after clicking the run button; but I suspect that is because my code snippet didn't have a return value.

**Comment by bryansh** [comment]
Closing as there hasn't been any response over the past 7 days, please reopen if there are further issues.
